---
title: "climate stats"
format: html
editor_options: 
  chunk_output_type: console
---


```{r}
#|label: setup
pacman::p_load(tidyverse, terra, lubridate)
```

```{r}
study_area <- read_sf("./outputs/vector/bonbon_buffer.gpkg")

rainfall <- rast("E:/data/climate_data/rainfall/agcd/agcd_v2-0-1_precip_total_r001_monthly_1900_2022.nc")
tmax <- rast("E:/data/climate_data/temperature/agcd_tmax_monthly_1971_2022.nc")

```

```{r}
summer_monthly_rain <- rainfall %>% 
  crop(st_transform(study_area, crs(.))) %>% 
  mask(st_transform(study_area, crs(.))) %>% 
  .[[month(time(.)) %in% c(12, 1, 2)]] %>% 
  mean() %>% 
  as.vector() %>% 
  mean(na.rm = T)

winter_monthly_rain <- rainfall %>% 
  crop(st_transform(study_area, crs(.))) %>% 
  mask(st_transform(study_area, crs(.))) %>% 
  .[[month(time(.)) %in% c(6, 7, 8)]] %>% 
  mean() %>% 
  as.vector() %>% 
  mean(na.rm = T)

summer_tmax <- tmax %>% 
  crop(st_transform(study_area, crs(.))) %>% 
  mask(st_transform(study_area, crs(.))) %>% 
  .[[month(time(.)) %in% c(12, 1, 2)]] %>% 
  mean() %>% 
  as.vector() %>% 
  mean(na.rm = T)

winter_tmax <- tmax %>% 
  crop(st_transform(study_area, crs(.))) %>% 
  mask(st_transform(study_area, crs(.))) %>% 
  .[[month(time(.)) %in% c(6, 7, 8)]] %>% 
  mean() %>% 
  as.vector() %>% 
  mean(na.rm = T)
```


