---
title: "Plot effects"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: setup
pacman::p_load(tidyverse, arrow, data.table, ggpubr, sf, terra)

# BB + surrounding. Min / Max values of cover types per pixel per year.
dat <- read_parquet("./outputs/tables/bonbon_minmax.parquet")

dat %>% 
  mutate(bonbon = as.factor(ifelse(str_detect(station, "Bon Bon"), 1, 0))) %>% 
  group_by(bonbon, year) %>%
  summarise(mean05 = mean(npv_05)) %>% 
  arrange(year) %>% 
  ggplot(aes(x = year, y = mean05, colour = bonbon)) +
  geom_line()

dat <- dat %>% 
  mutate(bonbon = ifelse(str_detect(station, "Bon Bon"), 1, 0),
         veg_groups = ifelse(str_detect(nvis, "Acacia"), "Acacia Open Woodlands", "Chenopod Shrublands"))

effects <- dat %>% 
  group_by(year, veg_groups) %>% 
  summarise(pv05_eff = mean(pv_05[bonbon == 1], na.rm = T) - mean(pv_05[bonbon == 0], na.rm = T),
            npv05_eff = mean(npv_05[bonbon == 1], na.rm = T) - mean(npv_05[bonbon == 0], na.rm = T),
            bare95_eff = mean(bare_95[bonbon == 1], na.rm = T) - mean(bare_95[bonbon == 0], na.rm = T))

effects$year <- ymd(effects$year, truncated = 2)
effects <- effects %>% 
  rename(date = "year")


study_area <- read_sf("./outputs/vector/bonbon_buffer.gpkg") %>% 
  st_transform("EPSG:28353")

rain <- rast("./outputs/raster/agcd_precipitation/agcd_v2-0-1_precip_total_r001_monthly_2000_2022.nc") %>% 
  # .[[which(time(.) >= as_date("2001-01-01"))]] %>% 
  # .[[which(time(.) < as_date("2023-01-01"))]] %>% 
  mask(study_area) %>% 
  crop(study_area)

monthly_rain <- roll(rain, 12, "mean", type = "to") %>%
  lapply(\(x) as.vector(x) %>%
                         mean(na.rm = T)) %>%
  unlist() %>%
  tibble(date = time(rain),
         rainfall = .,
         rain = as.factor(1)) %>%
  as.data.frame()

monthly_rain <- monthly_rain %>% 
  filter(!is.na(rainfall))

monthly_rain <- monthly_rain %>% 
  mutate(rainfall_anom = rainfall - median(rainfall))


#########################
### Plotting Function ###
#########################

plot_effects <- function(effects, cover_type, labelx, labely, legend_position) {
  df <- effects[[cover_type]] %>% 
    cbind(effects[,1:2], .) %>% 
    rename(values = 3)
  
  cover_name <- cover_type %>%
    str_split("_", simplify = T) %>%
    .[,1] %>% 
    str_sub(1, -3) %>%
    {ifelse(str_detect(., "pv"), str_to_upper(.), str_to_title(.))}
  
  means <- df %>%
    group_by(veg_groups) %>%
    summarise(mean_ref = mean(values[year(date) <= 2008]),
              mean_eff = mean(values[year(date) > 2008]))

  ggplot(df, aes(y = values, x = date, colour = veg_groups, linetype = veg_groups)) +
    geom_line(linewidth = 1) +
    # geom_smooth(data = df %>% filter(year(date) > 2008), method = lm, se = F) +
    # geom_smooth(data = df %>% filter(year(date) <= 2008), method = lm, se = F) +
    geom_segment(data = means, aes(x = min(df$date), y = mean_ref, xend = as_date("2008-09-01"), yend = mean_ref, colour = NULL), linewidth = 1) +
    geom_segment(data = means, aes(x = as_date("2009-02-01"), y = mean_eff, xend = max(df$date), yend = mean_eff, colour = NULL), linewidth = 1) +
    annotate("rect", xmin = as_date("2008-09-01"), xmax = as_date("2009-02-01"), ymin = min(df$values), ymax = Inf,
             alpha = .1, fill = "black") +
    annotate("rect", xmin = as_date("2009-02-01"), xmax = max(df$date), ymin = min(df$values), ymax = Inf,
             alpha = .1, fill = "#8DA0CB") +
    annotate("text", x = labelx, y = labely,
             label = "bold('Bon Bon Destocked')",
             hjust = 1, color = "#8DA0CB", parse = T,
             size = 10/.pt) +
    scale_y_continuous(limits = c(min(df$values), max(df$values)),
                       breaks = seq(floor(min(df$values)), floor(max(df$values)), 0.5),
                       expand = c(0, 0)) +
    scale_x_date(limits = as_date(c(min(df$date), max(df$date))),
               breaks = "2 year", 
               date_labels = "%Y", 
               expand = c(0, 0)) +
    labs(x = "Year",
         y = paste(cover_name, "Cover Difference (%)"),
         colour = "Vegetation Type",
         linetype = "Vegetation Type") +
    theme_classic() +
    theme(
      legend.background = element_rect(fill = "transparent"),
      legend.position = legend_position,
      legend.title = element_blank(),
      legend.text = element_text(face = "bold"),
      legend.key.width = unit(0.8, "cm"),
      plot.margin = margin(r = 0.5, unit = "cm")
    ) +
    guides(colour = guide_legend(override.aes = list(linewidth = 1.5)))
}

```



# PV
```{r}
plot_effects(effects, "pv05_eff", labelx = ymd("2015", truncated = 2),labely = 1.1, legend_position = c(0.80, 0.11)) +
  scale_colour_manual(values = c("#66C2A5", "#66C2A5"))

ggsave("./figures/pv_05_effect.png",
       width = 16,
       height = 8,
       units = "cm")

plot_effects(effects, "npv05_eff", labelx = ymd("2015", truncated = 2),labely = 1.5, legend_position = c(0.80, 0.11)) +
  scale_colour_manual(values = c("#FC8D62", "#FC8D62"))

ggsave("./figures/npv_05_effect.png",
       width = 16,
       height = 8,
       units = "cm")

plot_effects(effects, "bare95_eff", labelx = ymd("2015", truncated = 2),labely = 1.1, legend_position = c(0.18, 0.11)) +
  scale_colour_manual(values = c("#FFD92F", "#FFD92F"))

ggsave("./figures/bare_95_effect.png",
       width = 16,
       height = 8,
       units = "cm")
```

# NPV

```{r}
data_ibra <- dat[,.(eff = (mean(npv_05[station == "Bon Bon"], na.rm = T) - mean(npv_05[station != "Bon Bon"], na.rm = T))) , by = c("year", "ibra_sr")]
data_all <- dat[,.(eff = (mean(npv_05[station == "Bon Bon"], na.rm = T) - mean(npv_05[station != "Bon Bon"], na.rm = T))) , by = c("year")]

npv_05_ibra <- plot_effects(data_ibra, data_all) +
  labs(title = "NPV (5th Percentile)")

# ggsave("./figures/npv_05_ibra.png",
#        npv_05_ibra, 
#        width = 10,
#        height = 10 * 0.8)
```

# Bare

```{r}
data_ibra <- dat[,.(eff = (mean(bare_95[station == "Bon Bon"], na.rm = T) - mean(bare_95[station != "Bon Bon"], na.rm = T))) , by = c("year", "ibra_sr")]
data_all <- dat[,.(eff = (mean(bare_95[station == "Bon Bon"], na.rm = T) - mean(bare_95[station != "Bon Bon"], na.rm = T))) , by = c("year")]

ggplot(effects, aes(y = bare95_eff, x = year, colour = veg_groups)) +
  geom_line()

# ggsave("./figures/npv_05_ibra.png",
#        npv_05_ibra, 
#        width = 10,
#        height = 10 * 0.8)
```


# Versus rainfall anom

```{r}
# rain_effect <- merge(monthly_rain, effects, by = "date")

rain_effect <- merge(monthly_rain, effects, by = "date") %>% 
  group_by(date) %>% 
  summarise_all("mean")

ggplot(rain_effect %>% filter(date > as_date("2011-01-01")), aes(x = date, y = rainfall_anom)) +
  geom_line()
```

