---
title: "Plot effects"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: setup
pacman::p_load(tidyverse, arrow, data.table, ggpubr, sf, terra)

# BB + surrounding. Min / Max values of cover types per pixel per year.
dat <- read_parquet("./outputs/tables/bonbon_minmax.parquet")

dat %>% 
  mutate(bonbon = as.factor(ifelse(str_detect(station, "Bon Bon"), 1, 0))) %>% 
  group_by(bonbon, year) %>%
  summarise(mean05 = mean(npv_05)) %>% 
  arrange(year) %>% 
  ggplot(aes(x = year, y = mean05, colour = bonbon)) +
  geom_line()

dat <- dat %>% 
  mutate(bonbon = ifelse(str_detect(station, "Bon Bon"), 1, 0),
         veg_groups = ifelse(str_detect(nvis, "Acacia"), "Acacia Open Woodlands", "Chenopod Shrublands"))

effects <- dat %>% 
  group_by(year, veg_groups) %>% 
  summarise(pv05_eff = mean(pv_05[bonbon == 1], na.rm = T) - mean(pv_05[bonbon == 0], na.rm = T),
            npv05_eff = mean(npv_05[bonbon == 1], na.rm = T) - mean(npv_05[bonbon == 0], na.rm = T),
            bare95_eff = mean(bare_95[bonbon == 1], na.rm = T) - mean(bare_95[bonbon == 0], na.rm = T))

effects$year <- ymd(effects$year, truncated = 2)
effects <- effects %>% 
  rename(date = "year") %>% 
  mutate(management = as.factor(ifelse(date >= as_date("2008-01-01"), 1, 0)),
         .after = 2)

study_area <- read_sf("./outputs/vector/bonbon_buffer.gpkg") %>% 
  st_transform("EPSG:28353")

rain <- rast("./outputs/raster/agcd_precipitation/agcd_v2-0-1_precip_total_r001_monthly_1900_2022.nc") %>% 
  mask(study_area) %>% 
  crop(study_area)

monthly_rain <- roll(rain, 12, "mean", type = "to") %>%
  lapply(\(x) as.vector(x) %>%
                         mean(na.rm = T)) %>%
  unlist() %>%
  tibble(date = time(rain),
         rainfall = .,
         rain = as.factor(1)) %>%
  as.data.frame()

monthly_rain <- monthly_rain %>% 
  filter(!is.na(rainfall))

monthly_rain <- monthly_rain %>% 
  mutate(rainfall_anom = rainfall - median(rainfall))


#########################
### Plotting Function ###
#########################

plot_effects <- function(effects, cover_type, labelx, labely, legend_position) {
  df <- effects[[cover_type]] %>% 
    cbind(effects[,1:3], .) %>% 
    rename(values = 4)
  
  cover_name <- cover_type %>%
    str_split("_", simplify = T) %>%
    .[,1] %>% 
    str_sub(1, -3) %>%
    {ifelse(str_detect(., "pv"), str_to_upper(.), str_to_title(.))}

    
  means <- df %>%
    group_by(veg_groups) %>%
    summarise(mean_ref = mean(values[year(date) <= 2008]),
              mean_eff = mean(values[year(date) > 2008])
              )

  ggplot(df, aes(y = values, x = date, colour = veg_groups, linetype = veg_groups)) +
    geom_line(linewidth = 1) +
    geom_segment(data = means, aes(x = min(df$date), y = mean_ref, xend = as_date("2007-10-01"), yend = mean_ref, colour = NULL)) +
    geom_segment(data = means, aes(x = as_date("2008-02-01"), y = mean_eff, xend = max(df$date), yend = mean_eff, colour = NULL)) +
    annotate("rect", xmin = as_date("2007-10-01"), xmax = as_date("2008-02-01"), ymin = min(df$values), ymax = Inf,
             alpha = .1, fill = "black") +
    annotate("text", x = labelx, y = labely,
             label = "bold('Bon Bon Destocked\n(2008)')",
             hjust = 1, color = "grey30", parse = T,
             size = 10/.pt) +
    scale_y_continuous(limits = c(min(df$values), max(df$values)),
                       breaks = seq(plyr::round_any(min(df$values), 0.5, floor), plyr::round_any(max(df$values), 0.5, f = ceiling), 0.5),
                       expand = c(0, 0)) +
    scale_x_date(limits = as_date(c(min(df$date), max(df$date))),
               breaks = "2 year", 
               date_labels = "%Y", 
               expand = c(0, 0)) +
    labs(x = "Year",
         y = paste("Persistent", cover_name, "Cover Difference (% cover) "),
         colour = "Vegetation Type",
         linetype = "Vegetation Type") +
    theme_classic() +
    theme(
      axis.title = element_text(size = 10, face = "bold"),
      axis.text = element_text(size = 10),
      legend.background = element_rect(fill = "transparent"),
      legend.position = legend_position,
      legend.title = element_blank(),
      legend.text = element_text(face = "bold"),
      legend.key.width = unit(0.8, "cm"),
      plot.margin = margin(t = 0.5, b = 0.2, r = 0.5, unit = "cm")
    ) +
    guides(colour = guide_legend(override.aes = list(linewidth = 1.5)))
}

```



# PV
```{r}
p2 <- ggplot(monthly_rain, aes(x = date, y = (rainfall * 12))) +
  geom_line(colour = "steelblue") +
  geom_hline(yintercept = mean(monthly_rain$rainfall*12), colour = "grey", linetype = "dashed", linewidth = 0.5) +
  scale_x_date(limits = as_date(c(as_date("2001-01-01"), as_date("2023-01-01"))), 
               breaks = "2 year", date_labels = "%Y", 
               expand = c(0, 0)) +
  scale_y_continuous(breaks = c(100, 250, 400), limits = c(0, 400)) +
  labs(y = "12 Month\nRainfall (mm)",
       x = "Year") +
  theme_classic() +
  theme(
    axis.title = element_text(face = "bold"),
    axis.text = element_text(size = 10)
  )

pv_eff <- plot_effects(effects, "pv05_eff", labelx = ymd("2013-09", truncated = 1),labely = 1.05, legend_position = c(0.80, 0.11)) +
  scale_colour_manual(values = c("#66C2A5", "#66C2A5"))

ggpubr::ggarrange(pv_eff +
                    ggpubr::rremove("x.title") +
                    ggpubr::rremove("x.text"), 
                  p2,
                  ncol = 1,
                  heights = c(1, 0.3),
                  align = "v")

ggsave("./figures/figure_6_pv_cover_difference.png",
       width = 16,
       height = 12,
       dpi = 300,
       units = "cm")

npv_eff <- plot_effects(effects, "npv05_eff", labelx = ymd("2013-09", truncated = 1),labely = 1.5, legend_position = c(0.80, 0.11)) +
  # geom_line(data = monthly_rain, aes(x = date, y = rainfall_anom/100, colour = NULL, linetype = NULL)) +
  # scale_y_continuous(
  #   name = "Fractional Cover (%)",
  #   sec.axis = sec_axis(~.*100, name = "Monthly Rainfall (mm)")
  #   ) +
  scale_colour_manual(values = c("#8DA0CB", "#8DA0CB"))

ggpubr::ggarrange(npv_eff +
                    ggpubr::rremove("x.title") +
                    ggpubr::rremove("x.text"), 
                  p2,
                  ncol = 1,
                  heights = c(1, 0.3),
                  align = "v")


ggsave("./figures/figure_7_npv_cover_difference.png",
       width = 16,
       height = 12,
       dpi = 300,
       units = "cm")

bare_eff <- plot_effects(effects, "bare95_eff", labelx = ymd("2013-09", truncated = 1),labely = 1, legend_position = c(0.18, 0.11)) +
  scale_colour_manual(values = c("#FC8D62", "#FC8D62"))

ggpubr::ggarrange(bare_eff +
                    ggpubr::rremove("x.title") +
                    ggpubr::rremove("x.text"), 
                  p2,
                  ncol = 1,
                  heights = c(1, 0.3),
                  align = "v")


ggsave("./figures/figure_8_bare_cover_difference.png",
       width = 16,
       height = 12,
       dpi = 300,
       units = "cm")
```