---
title: "Total vegetation fractional cover"
author: "Angus Retallack"
date: "2022-08-07"
output: html_document
editor_options: 
  chunk_output_type: console
---

Create Total Vegetation Cover (TVC) from NPV and PV fractional cover bands

Data inputs are pre-processed 8-day or monthly fractional cover rasters from 
PreProcess.rmd. 

Annual TVC is produced from the monthly product.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse, terra, sf)
dataset <- "monthly" # 8day or monthly
```

# Import Data

```{r}
basePath <- "E:/Data/MODIS"
if (dataset == "8day") {
  dataPath <- file.path(basePath, "GuerschmanFC/8day/Processed")
  outputPath <- file.path(dataPath, "TVC")
}

if (dataset == "monthly") {
  dataPath <- file.path(basePath, "GuerschmanFC/Monthly/Processed")
  outputPath <- file.path(dataPath, "TVC")
}

filePaths <- list.files(dataPath, "*.tif$", full.names = TRUE)

FC <- rast(filePaths)

```

# Calculate TVC

TVC is the sum of NPV and PV bands of the fractional cover product

```{r}
TVC <- FC[[which(str_detect(names(FC), "_2"))]] + FC[[which(str_detect(names(FC), "_3"))]]
```


# Write TVC

```{r, eval = FALSE}
names <- names(TVC)

if (dataset == "8day") {
  names(TVC) <- str_replace(names, "_2", "_TVC8.tif")
}

if (dataset == "monthly") {
names(TVC) <- str_replace(names, "_2", "_TVCm.tif")
}

writeRasters <- function(rasters) {
  writeRaster(rasters, 
              file.path(outputPath, names(rasters)), 
              datatype = "INT1U", 
              overwrite = TRUE
              )
}

lapply(TVC, writeRasters)
```

