---
title: "Composite PV & NPV"
author: "Angus Retallack"
date: "2022-10-10"
output: html_document
---

Create Total Vegetation Cover (TVC) from NPV and PV fractional cover bands

Data inputs are pre-processed 8-day or monthly fractional cover rasters from 
PreProcess.rmd. 

Annual TVC is produced from the monthly product.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse, terra, sf)
```

# Import Data

```{r}
basePath <- "E:/Data/MODIS"

dataPath <- file.path(basePath, "GuerschmanFC/Monthly/Processed")
outputPath <- file.path(dataPath, "TVC")

filePaths <- list.files(dataPath, "*.tif$", full.names = TRUE)

FC <- rast(filePaths)
```
# Extract PV and NPV

```{r}
PV <- FC[[which(str_detect(names(FC), "_2"))]]
NPV <- FC[[which(str_detect(names(FC), "_3"))]]
```

# Create annual composite

## PV

```{r}
fileYears <- names(PV) %>% 
  str_split(., pattern = "\\.", simplify = TRUE) %>% 
  .[ , 4] %>% 
  str_replace("A", "")

fileMonths <- names(PV) %>% 
  str_split(., pattern = "\\.", simplify = TRUE) %>% 
  .[ , 5]


fullYears <- floor(length(fileMonths) / 12) # Number of full years in data
# fullQuarters <- floor(length(fileMonths) / 3) # Number of full quarters in data

PVa <- vector("list", fullYears)

for (y in 1:fullYears) {
  yearsIndex <- which(fileYears == unique(fileYears)[y])
  PVyear <- PV[[yearsIndex]]
  PVa[[y]] <- mean(PVyear)
}

PVa <- rast(PVa)

names <- names(PV) %>% 
str_replace("_2", "_PVa.tif") %>% 
.[1:length(names(PVa))] %>% 
str_split(., "\\.", simplify = TRUE)

# Remove month info
names <- names[ , -5]
names[ , 4] <- paste0("A", rep(seq(2001, max(unique(fileYears)[1:fullYears]), 1))[1:nrow(names)])

names(PVa) <- apply(names, 1, str_flatten, ".")
```

## NPV

```{r}
NPVa <- vector("list", fullYears)

for (y in 1:fullYears) {
  yearsIndex <- which(fileYears == unique(fileYears)[y])
  NPVyear <- NPV[[yearsIndex]]
  NPVa[[y]] <- mean(NPVyear)
}

NPVa <- rast(NPVa)

names <- names(NPV) %>% 
str_replace("_3", "_NPVa") %>% 
.[1:length(names(NPVa))] %>% 
str_split(., "\\.", simplify = TRUE)

# Remove month info
names <- names[ , -5]
names[ , 4] <- paste0("A", rep(seq(2001, max(unique(fileYears)[1:fullYears]), 1))[1:nrow(names)])

names(NPVa) <- apply(names, 1, str_flatten, ".")
```


```{r}
writeRasters <- function(rasters) {
  writeRaster(rasters, 
              file.path(outputPath, names(rasters)), 
              datatype = "INT1U", 
              overwrite = TRUE
              )
}


outputPath <- file.path(dataPath, "PV", "PVa")
lapply(PVa, writeRasters)

outputPath <- file.path(dataPath, "NPV", "NPVa")
lapply(NPVa, writeRasters)

```


# Create quarterly composite

## PV

```{r}
fileYears <- names(PV) %>% 
  str_split(., pattern = "\\.", simplify = TRUE) %>% 
  .[ , 4] %>% 
  str_replace("A", "")

fileMonths <- names(PV) %>% 
  str_split(., pattern = "\\.", simplify = TRUE) %>% 
  .[ , 5]


fullYears <- floor(length(fileMonths) / 12) # Number of full years in data
# fullQuarters <- floor(length(fileMonths) / 3) # Number of full quarters in data

PVa <- vector("list", fullYears)

for (y in 1:fullYears) {
  yearsIndex <- which(fileYears == unique(fileYears)[y])
  PVyear <- PV[[yearsIndex]]
  PVa[[y]] <- mean(PVyear)
}

PVa <- rast(PVa)

names <- names(PV) %>% 
str_replace("_2", "_PVa.tif") %>% 
.[1:length(names(PVa))] %>% 
str_split(., "\\.", simplify = TRUE)

# Remove month info
names <- names[ , -5]
names[ , 4] <- paste0("A", rep(seq(2001, max(unique(fileYears)[1:fullYears]), 1))[1:nrow(names)])

names(PVa) <- apply(names, 1, str_flatten, ".")
```

## NPV

```{r}
NPVa <- vector("list", fullYears)

for (y in 1:fullYears) {
  yearsIndex <- which(fileYears == unique(fileYears)[y])
  NPVyear <- NPV[[yearsIndex]]
  NPVa[[y]] <- mean(NPVyear)
}

NPVa <- rast(NPVa)

names <- names(NPV) %>% 
str_replace("_3", "_NPVa") %>% 
.[1:length(names(NPVa))] %>% 
str_split(., "\\.", simplify = TRUE)

# Remove month info
names <- names[ , -5]
names[ , 4] <- paste0("A", rep(seq(2001, max(unique(fileYears)[1:fullYears]), 1))[1:nrow(names)])

names(NPVa) <- apply(names, 1, str_flatten, ".")
```


```{r}
writeRasters <- function(rasters) {
  writeRaster(rasters, 
              file.path(outputPath, names(rasters)), 
              datatype = "INT1U", 
              overwrite = TRUE
              )
}


outputPath <- file.path(dataPath, "PV", "PVa")
lapply(PVa, writeRasters)

outputPath <- file.path(dataPath, "NPV", "NPVa")
lapply(NPVa, writeRasters)

```







