---
title: "Calculate Quarterly + Annual TVC"
author: "Angus Retallack"
date: "2022-08-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse, terra)
# Period to calculate for  
period <- "quarterly" # quarterly or annual
```

# Import monthly TVC  

```{r}
filePath <- "E:/Data/MODIS/GuerschmanFC/Monthly/Processed/TVC"  

TVCm <- rast(list.files(filePath, "*.tif$", full.names = TRUE))
```
# File dates

Vector of years and months of files to use for selecting periods for averaging

```{r years and months}
fileYears <- names(TVCm) %>% 
  str_split(., pattern = "\\.", simplify = TRUE) %>% 
  .[ , 4] %>% 
  str_replace("A", "")

fileMonths <- names(TVCm) %>% 
  str_split(., pattern = "\\.", simplify = TRUE) %>% 
  .[ , 5]


fullYears <- floor(length(fileMonths) / 12) # Number of full years in data
fullQuarters <- floor(length(fileMonths) / 3) # Number of full quarters in data
```


# Calculate TVC annual / quarterly means

```{r}
if (period == "annual") {
  # List for annual TVC number of years for which there are a full 12 months
  TVCa <- vector("list", fullYears)
} else {
  # List for quarterly TVC number of quarters for which there a full 3 months
  TVCq <- vector("list", fullQuarters)
}

if (period == "annual") {
  for (y in 1:fullYears) {
    yearsIndex <- which(fileYears == unique(fileYears)[y])
    TVCyear <- TVCm[[yearsIndex]]
    TVCa[[y]] <- mean(TVCyear)
  }
  
  TVCa <- rast(TVCa)
  
  names <- names(TVCm) %>% 
  str_replace("TVCm", "TVCa") %>% 
  .[1:length(names(TVCa))] %>% 
  str_split(., "\\.", simplify = TRUE)
  
  # Remove month info
  names <- names[ , -5]
  names[ , 4] <- paste0("A", rep(seq(2001, max(unique(fileYears)[1:fullYears]), 1))[1:nrow(names)])
  
  names(TVCa) <- apply(names, 1, str_flatten, ".")
} 

if (period == "quarterly") {
  for (y in 1:length(unique(fileYears))) {
    yearsIndex <- which(fileYears == unique(fileYears)[y])
    TVCyears <- TVCm[[yearsIndex]]
    for (q in seq(1, (length(fileMonths) - length(fileMonths) %% 3), 1)) {
      monthsIndex <- as.numeric(fileMonths[q:(q + 2)])
      TVCquarters <- TVCyears[[monthsIndex]]
      quarterNumber <- ((q %/% 3) + 1) + ((y - 1) * 4)
      TVCq[[quarterNumber]] <- mean(TVCquarters)
    }
  }
  
  TVCq <- rast(TVCq)
  
  names <- names(TVCm) %>% 
    str_replace("TVCm", "TVCq") %>% 
    .[1:length(names(TVCq))] %>% 
    str_split(., "\\.", simplify = TRUE)
  names[ , 5] <- rep(c("01", "02", "03", "04"), times = length(unique(fileYears)))[1:length(names(TVCq))]
  names[ , 4] <- paste0("A", rep(seq(2001, max(fileYears), 1), each = 4)[1:length(names(TVCq))])
  
  names(TVCq) <- apply(names, 1, str_flatten, ".")
}


```

# Write TIFs

```{r, eval = FALSE}
writeRasters <- function(rasters) {
  writeRaster(rasters, 
              file.path(outputPath, names(rasters)), 
              datatype = "INT1U", 
              overwrite = TRUE
              )
}


if (period == "annual") {
  outputPath <- file.path(filePath, "TVCa")
  lapply(TVCa, writeRasters)
  
} else {
  outputPath <- file.path(filePath, "TVCq")
  lapply(TVCq, writeRasters)
}
```

