---
title: "Calculate Percentiles"
author: "Angus Retallack"
date: "2022-08-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse, terra, sf)

dataset <- "EVI" # Raster product of interest (TVC8day TVCm or EVI)

# EVI dataset comes from PreProcess.rmd
# TVC datasets came from Create_TVC.rmd
```

# File paths

```{r}
if (dataset == "TVC8day") {
  dataPath <- "E:/Data/MODIS/GuerschmanFC/8day/Processed/TVC"
  filePaths <- list.files(dataPath, "*.tif$", full.names = TRUE)
  outputPath <- file.path(dataPath, "Percentiles")
}

if (dataset == "TVCm") {
  dataPath <- "E:/Data/MODIS/GuerschmanFC/Monthly/Processed/TVC"
  filePaths <- list.files(dataPath, "*.tif$", full.names = TRUE)
  outputPath <- file.path(dataPath, "Percentiles")
}

if (dataset == "EVI") {
  dataPath <- "E:/Data/MODIS/VI_16Days_500m_v6/EVI/Processed"
  filePaths <- list.files(dataPath, "*.tif$", full.names = TRUE)
  outputPath <- file.path(dataPath, "Percentiles")
}
```


# Import raster

```{r}
rasters <- rast(filePaths)
```


# Percentiles relative to pixel

```{r Pixel percentiles}
rastArray <- as.array(rasters)

# Percentile array. Set non-NA values to NA
ppArray <- rastArray
ppArray[!is.na(ppArray)] <- NA

# Loop through each "pixel" (row / column) and calculate its percentile 
for (r in 1:nrow(rastArray)) {
  for (c in 1:ncol(rastArray)) {
    ppArray[r, c, ] <-  ntile(rastArray[r, c, ], n = 100)
  }
}

# Test percentiles are working correctly
# plot(rastArray[100, 100, ], ppArray[100, 100, ])

# Convert percentiles array to SpatRaster
percentiles <- rast(ppArray, extent = ext(rasters[[1]]), crs = crs(rasters[[1]]))

names <- names(rasters)

if (dataset %in% c("TVC8day", "TVCm")) { 
  names <- str_replace(names, ".tif", "_Percentiles.tif")
}

if (dataset == "EVI") {
  names <- paste0(names, "_Percentiles.tif")
}

# Change names
names(percentiles) <- names

# Function to write rasters to .tif
writeRasters <- function(rasters) {
  writeRaster(rasters, file.path(outputPath, names(rasters)), datatype = "INT1U", overwrite = TRUE)
}

lapply(percentiles, writeRasters)
```
