---
title: "Filter_Raster_Dataframe"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: setup
pacman::p_load(tidyverse, data.table)

df <- arrow::open_dataset("./outputs/tables/full_dataframe.parquet") %>% 
  filter(is.na(water)) %>% 
  filter(is.na(fence_buffer)) %>%
  filter(!is.na(station)) %>% 
  filter(land_system_id != 770) %>% 
  mutate(year = year(as_date(date)),
         ddate = decimal_date(as_date(date)),
         month = month(as_date(date)), .after = 5)


  # filter(!station %in% c("Lake Torrens NP", "Other", "Kati Thanda-Lake Eyre NP", "Lake Gairdner NP", "Salt Lake", "Lake Everard", "Coward Springs Railway Siding", "Wadma Kadarbu Mound Springs CP", "Olympic Dam")) %>% 
  # filter(!nvis_group %in% c("Inland aquatic - freshwater, salt lakes, lagoons", "Naturally bare - sand, rock, claypan, mudflat", "Cleared, non-native vegetation, buildings")) 
```

# Filter DF for Bon Bon component of study

Remove stocking columns Remove agcd data (for now) Remove water and fenceline buffer and study zone as these have already been used to filter Remove station area (not necessary)

```{r}
bonbon <- df %>%
  filter(study_zone %in% c(1, 2)) %>%
  select(-c("water", "fence_buffer", "study_zone", "land_system_id"))

bonbon <- bonbon %>% 
  as.data.table()

bonbon$study_zone %>% unique()

bonbon %>% 
  group_by(nvis_group) %>% 
  summarise(n = n()) %>% 
  arrange(desc(n)) %>% 
  ggplot(aes(x = reorder(nvis_group, n), y = n)) +
  geom_col()

bonbon %>% 
  group_by(nvis_group) %>% 
  summarise(n = n()) %>% 
  arrange(desc(n)) %>% 
  select(n) %>%
  unlist() %>% 
  as.numeric() %>% 
  {sum(.[1:4]) / sum(.)}

bonbon <- bonbon %>% 
  filter(nvis_group %in% c("Acacia Open Woodlands", "Chenopod Shrublands, Samphire Shrublands and Forblands", "Acacia Shrublands", "Acacia Forests and Woodlands")) %>% 
  filter(!station %in% c("Lake Gairdner NP")) %>% 
  filter(!ibra_subregion %in% c("Gawler Lakes"))

```
## Write Bon Bon parquet

```{r}
arrow::write_parquet(bonbon, "./outputs/tables/bonbon.parquet")
```

