---
title: "basic_analysis"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: setup
pacman::p_load(tidyverse, arrow, data.table, ggpubr)

# BB + surrounding. Min / Max values of cover types per pixel per year.
dat <- read_parquet("./outputs/tables/bonbon_minmax.parquet") %>% 
  mutate(cyear = year - 2008, .after = 2)

#########################
### Plotting Function ###
#########################

plot_effects <- function(data_ibra, data_all) {
  means <- data_ibra %>%
    group_by(ibra_sr) %>%
    summarise(mean_ref = mean(eff[which(year <= 2008)]),
              mean_eff = mean(eff[which(year > 2008)]))
  
  
  plot <- ggplot(data_ibra, aes(x = year, y = eff, colour = ibra_sr)) +
    geom_line(linewidth = 0.7) +
    geom_line(data = data_all, aes(colour = "All Regions"), linewidth = 1.5) +
    geom_segment(data = means, aes(x = min(data_ibra$year), xend = 2008, y = mean_ref, yend = mean_ref),
                 linewidth = 1.5) +
    geom_segment(data = means, aes(x = 2008, xend = max(data_ibra$year), y = mean_eff, yend = mean_eff),
                 linewidth = 1.5) +
    geom_vline(xintercept = 2008, colour = "red", linewidth = 1.5) +
    scale_colour_manual(values = c("#000000", RColorBrewer::brewer.pal(8, "Set2")[c(2,3,5)]),
                        labels = c('All Regions', 'Breakaways', 'Kingoonya', 'Roxby')) +
    labs(title = "PV (5th Percentile)",
         x = "Year",
         y = "Effect (% Cover Anomaly)",
         colour = "IBRA Sub-Region") +
    theme_classic() +
    theme(
      legend.title = element_blank(),
      legend.position = c(0.11, 0.20),
      legend.background = element_rect(fill = "transparent", colour = "transparent"),
      axis.title = element_text(size = 10, face = "bold"),
      axis.title.x = element_text(vjust = unit(-0.1, "cm")),
      axis.title.y = element_text(margin = unit(c(0, 0.2, 0, 0), "cm")),
      axis.text = element_text(size = 10)
    )
  
  return(plot)
}
```

## PV 5th percentile

```{r}
# mean of pv min per year for bon bon
# minus mean of pv min per year for all stations
# basically, the deviation of bon bon from the surrounding stations.
dat_pv5 <- dat[,.(eff = (mean(pv_05[station == "Bon Bon"], na.rm = T) - mean(pv_05[station != "Bon Bon"], na.rm = T))) , by = year]

pv_05 <- ggplot(dat_pv5, aes(year, eff)) +
  geom_line() +
  # geom_smooth(data = dat_1[(year <= 2008) == T], method = "lm", se = F) +
  # geom_smooth(data = dat_1[(year > 2008) == T], method = "lm", se = F) +
  geom_segment(aes(x = min(dat_pv5$year), xend = 2008, y = mean(dat_pv5[(year <= 2008) == T]$eff), yend = mean(dat_pv5[(year <= 2008) == T]$eff)), 
               colour = "blue",
               linewidth = 1.5) +
  geom_segment(aes(x = 2008, xend = max(dat_pv5$year), y = mean(dat_pv5[(year > 2008) == T]$eff), yend = mean(dat_pv5[(year > 2008) == T]$eff)), 
               colour = "blue",
               linewidth = 1.5) +
  geom_vline(xintercept = 2008, colour = "red", linewidth = 1.5) +
  labs(title = "PV (5th Percentile)")
```

# NPV

## 5th percentile

```{r}
dat_npv5 <- dat[,.(eff = (mean(npv_05[station == "Bon Bon"], na.rm = T) - mean(npv_05[station != "Bon Bon"], na.rm = T))) , by = year]

npv_05 <- ggplot(dat_npv5, aes(year, eff)) +
  geom_line() +
  geom_segment(aes(x = min(dat_npv5$year), xend = 2008, y = mean(dat_npv5[(year <= 2008) == T]$eff), yend = mean(dat_npv5[(year <= 2008) == T]$eff)),
               colour = "blue",
               linewidth = 1.5) +
  geom_segment(aes(x = 2008, xend = max(dat_npv5$year), y = mean(dat_npv5[(year > 2008) == T]$eff), yend = mean(dat_npv5[(year > 2008) == T]$eff)),
               colour = "blue",
               linewidth = 1.5) +
  geom_vline(xintercept = 2008, colour = "red", size = 1.5) +
  labs(title = "NPV (5th Percentile)")
```

# Bare


## 95th Percentile

```{r}
dat_bare95 <- dat[,.(eff = (mean(bare_95[station == "Bon Bon"], na.rm = T) - mean(bare_95[station != "Bon Bon"], na.rm = T))) , by = year]

bare_95 <- ggplot(dat_bare95, aes(year, eff)) +
  geom_line() +
  geom_segment(aes(x = min(dat_bare95$year), xend = 2008, y = mean(dat_bare95[(year <= 2008) == T]$eff), yend = mean(dat_bare95[(year <= 2008) == T]$eff)),
               colour = "blue",
               linewidth = 1.5) +
  geom_segment(aes(x = 2008, xend = max(dat_bare95$year), y = mean(dat_bare95[(year > 2008) == T]$eff), yend = mean(dat_bare95[(year > 2008) == T]$eff)),
               colour = "blue",
               linewidth = 1.5) +
  geom_vline(xintercept = 2008, colour = "red", size = 1.5) +
  labs(title = "Bare (95th Percentile)")
```

```{r}
# 5th/95th 
ggpubr::ggarrange(pv_05, npv_05, bare_05, 
                  pv_95, npv_95, bare_95,
                  ncol = 3,
                  nrow = 2)
```

# Group by IBRA SR

## PV

# PV

### 5th

```{r}
data_ibra <- dat[,.(eff = (mean(pv_05[station == "Bon Bon"], na.rm = T) - mean(pv_05[station != "Bon Bon"], na.rm = T))) , by = c("year", "ibra_sr")]
data_all <- dat[,.(eff = (mean(pv_05[station == "Bon Bon"], na.rm = T) - mean(pv_05[station != "Bon Bon"], na.rm = T))) , by = c("year")]

pv_05_ibra <- plot_effects(data_ibra, data_all) +
  labs(title = "PV (5th Percentile)")

# ggsave("./figures/pv_05_ibra.png",
#        pv_05_ibra, 
#        width = 10,
#        height = 10 * 0.8)
```

## NPV

### 5th

```{r}
data_ibra <- dat[,.(eff = (mean(npv_05[station == "Bon Bon"], na.rm = T) - mean(npv_05[station != "Bon Bon"], na.rm = T))) , by = c("year", "ibra_sr")]
data_all <- dat[,.(eff = (mean(npv_05[station == "Bon Bon"], na.rm = T) - mean(npv_05[station != "Bon Bon"], na.rm = T))) , by = c("year")]

npv_05_ibra <- plot_effects(data_ibra, data_all) +
  labs(title = "NPV (5th Percentile)")

# ggsave("./figures/npv_05_ibra.png",
#        npv_05_ibra, 
#        width = 10,
#        height = 10 * 0.8)
```

## Bare

### 95th

```{r}
data_ibra <- dat[,.(eff = (mean(bare_95[station == "Bon Bon"], na.rm = T) - mean(bare_95[station != "Bon Bon"], na.rm = T))) , by = c("year", "ibra_sr")]
data_all <- dat[,.(eff = (mean(bare_95[station == "Bon Bon"], na.rm = T) - mean(bare_95[station != "Bon Bon"], na.rm = T))) , by = c("year")]

bare_95_ibra <- plot_effects(data_ibra, data_all) +
  labs(title = "Bare (95th Percentile)")

# ggsave("./figures/npv_05_ibra.png",
#        npv_05_ibra, 
#        width = 10,
#        height = 10 * 0.8)
```


```{r}
ggpubr::ggarrange(pv_05_ibra + rremove("xlab") + rremove("x.text"), 
                  npv_05_ibra + rremove("legend") + rremove("xlab") + rremove("x.text"), 
                  bare_95_ibra + rremove("legend"),
                  nrow = 3)


ggsave("./figures/anomalies_all.png",
       width = 16,
       height = 24,
       units = "cm")
```

