---
title: "Composite rainfall datasets"
format: html
---

```{r}
#| label: setup
pacman::p_load(terra, tidyverse, stringr)
```

# Load files

```{r}
fc_path <- "./outputs/raster/guerschman_fc_monthly/"
pv <- list.files(fc_path, "*.nc$", full.names = T) %>% 
  {.[which(str_detect(., "_pv"))]} %>% 
  rast()
npv <- list.files(fc_path, "*.nc$", full.names = T) %>% 
  {.[which(str_detect(., "_npv"))]} %>% 
  rast()
bare <- list.files(fc_path, "*.nc$", full.names = T) %>% 
  {.[which(str_detect(., "_bare"))]} %>% 
  rast()
```

# Annual min

```{r}
min_12mo_pv <- roll(pv, 12, type = "from", fun = "min")
min_12mo_npv <- roll(npv, 12, type = "from", fun = "min")
min_12mo_bare <- roll(bare, 12, type = "from", fun = "min")

writeCDF(min_12mo_pv, file.path(fc_path, "rolling", paste0("fc_monthly_pv_20010101_20230101_12mo_min.nc")), varname = "pv_12mo_min", compression = 6, overwrite = T)
writeCDF(min_12mo_npv, file.path(fc_path, "rolling", paste0("fc_monthly_npv_20010101_20230101_12mo_min.nc")), varname = "npv_12mo_min", compression = 6, overwrite = T)
writeCDF(min_12mo_bare, file.path(fc_path, "rolling", paste0("fc_monthly_bare_20010101_20230101_12mo_min.nc")), varname = "bare_12mo_min", compression = 6, overwrite = T)
```

# Annual max

```{r}
max_12mo_pv <- roll(pv, 12, type = "from", fun = "max")
max_12mo_npv <- roll(npv, 12, type = "from", fun = "max")
max_12mo_bare <- roll(bare, 12, type = "from", fun = "max")

writeCDF(max_12mo_pv, file.path(fc_path, "rolling", paste0("fc_monthly_pv_20010101_20230101_12mo_max.nc")), varname = "pv_12mo_max", compression = 6, overwrite = T)
writeCDF(max_12mo_npv, file.path(fc_path, "rolling", paste0("fc_monthly_npv_20010101_20230101_12mo_max.nc")), varname = "npv_12mo_max", compression = 6, overwrite = T)
writeCDF(max_12mo_bare, file.path(fc_path, "rolling", paste0("fc_monthly_bare_20010101_20230101_12mo_max.nc")), varname = "bare_12mo_max", compression = 6, overwrite = T)
```