---
title: "Define study area"
date: 21/08/2022
author: Angus Retallack
format: html
---

```{r}
#| label: setup
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse, terra, sf)
```

Generate study extent that will be used to crop rasters to desired region
Saves bounding box as .gpkg 

```{r Import vector data}
# Stations of interest. Raster cropped to this extent
stations_include <- c("Stuart Creek", "Andamooka", "Purple Downs", "Roxby Downs", "Mulgaria", "Olympic Dam", "Yellabinna RR") 

### Pastoral stations ###
stations <- read_sf("./data/shp/pastoral_stations.gpkg") %>% 
  st_cast("POLYGON")
stations$geometry <- st_transform(st_geometry(stations), "EPSG:28353")

names(stations) <- tolower(names(stations))

calc_angle <- function(lon,lat) {
  cent_lon <- mean(lon)
  cent_lat <- mean(lat)
  ang <- atan2(lat - cent_lat, lon - cent_lon)

  return(ang)
}  

bbox <- stations[which(stations$name %in% stations_include), ] %>%
  st_coordinates() %>% 
  as_tibble() %>%
  summarise(xmin = min(X),ymin = min(Y), xmax = max(X),  ymax = max(Y)) %>%
  gather(x,lon,c('xmin','xmax')) %>%
  gather(y,lat,c('ymin','ymax')) %>%
  st_as_sf(coords = c('lon','lat'), crs = 28353, remove = F) %>%
  mutate(angle = calc_angle(lat,lon)) %>%
  arrange(angle) %>%
  summarise(do_union = FALSE) %>%
  st_cast("POLYGON") %>% 
  st_geometry() %>% 
  st_transform("EPSG:4326")

st_write(st_transform(bbox, "EPSG: 28353"), "./outputs/vector/study_area.gpkg", append = F)
```
