---
title: "Process static datasets"
format: html
---

```{r}
#| label: setup
pacman::p_load(tidyverse, sf, terra)

study_area <- read_sf("./outputs/vector/study_area.gpkg")
# study area as extent coords
study_extent <- study_area %>% ext()
```

# Stations

```{r}
stations <- read_sf("./data/vector/pastoral_stations.gpkg") %>% 
  vect() %>%
  crop(study_extent) %>% 
  st_as_sf()

write_sf(stations, "./outputs/vector/pastoral_stations.gpkg")
```

# Paddocks

```{r}
paddocks <- read_sf("./data/vector/pastoral_paddocks.gpkg") %>% 
  .[-which(st_is_empty(.)),] %>% 
  vect() %>%
  crop(study_extent) %>%
  st_as_sf()

write_sf(paddocks, "./outputs/vector/pastoral_paddocks.gpkg")
```

# IBRA Regions

```{r}
ibra <- read_sf("./data/vector/ibra_subregions.gpkg") %>%
  vect() %>%
  crop(study_extent) %>% 
  st_as_sf()

st_write(ibra, "./outputs/vector/ibra_subregions.gpkg", delete_layer = T)
```

# Pastoral Landsystems

```{r}
pastoral_landsystems <- read_sf("./data/vector/pastoral_landsystems.gpkg") %>%
  vect() %>%
  crop(study_extent) %>% 
  st_as_sf()

st_write(pastoral_landsystems, "./outputs/vector/pastoral_landsystems.gpkg", delete_layer = T)
```

# Station Fence Buffer

500 m buffer around station fences

```{r}
fences <- read_sf("./data/vector/pastoral_stations.gpkg") %>%
  st_transform("EPSG:28353") %>% 
  st_cast("POLYGON") %>%
  st_cast("LINESTRING") %>%
  st_buffer(500) %>%
  st_union() %>%
  as_tibble() %>%
  add_column(fence = 1) %>%
  st_as_sf() %>% 
  vect() %>% 
  crop(study_extent)

writeVector(fences, "./outputs/vector/fences.gpkg", overwrite = T)
```


# Dog Fence

```{r}
dog_fence <- read_sf("./data/vector/dog_fence.gpkg") %>% 
  st_intersection(study_area) %>% 
  as_tibble() %>% 
  add_column(area = st_area(.$geom),
             inside = as.numeric(0)) %>% 
  arrange(area)

dog_fence <- rbind(dog_fence$geom[1:5] %>%
                     st_union() %>%
                     as_tibble(),
                   dog_fence$geom[6] %>%
                     add_column(inside = c(0, 1)) %>%
                     st_as_sf())

write_sf(dog_fence, "./outputs/vector/dog_fence.gpkg")
```

# Bon Bon 10 km Buffer

```{r}
## Areas that are within a 10 km buffer of Bon Bon for finer-scale modelling
bonbon <- read_sf("./data/vector/pastoral_stations.gpkg") %>% 
  as_tibble() %>% 
  .[which(.$NAME == "Bon Bon"), ] %>% 
  st_as_sf() %>% 
  st_geometry()

zone <- bonbon %>% 
  st_buffer(10000) %>% 
  st_intersection(c(., bonbon)) %>% 
  as_tibble() %>% 
  add_column(zone = c(2, 1)) %>% 
  st_as_sf()

zone[is.na(zone)] <- 3

write_sf(zone, "./outputs/vector/bonbon_buffer.gpkg")
```

# Water
Water polygons, used to mask pixels to exclude

```{r}
water <- read_sf("./data/vector/water_courses.gpkg") %>%
  vect() %>% 
  crop(study_extent) %>% 
  st_as_sf() %>% 
  st_buffer(250) # Buffer by 250 m to be sure

write_sf(water, "./outputs/vector/water_courses.gpkg")
```
