---
title: "Process AGCD"
format: html
---

```{r}
#| label: setup
pacman::p_load(terra, tidyverse, stringr, sf)

# Load study area
studyExtent <- read_sf("./outputs/vector/study_area.gpkg") %>% st_geometry()
```


```{r}
filePath <- "E:/Data/Climate_Data/AGCD/Precipitation" %>% 
  list.files("*.nc$", full.names = T)
outputPath <- "./outputs/raster/agcd_precipitation"

rasters <- rast(filePath)
# Select images within time range
rasters <- rasters[[-which(time(rasters) < lubridate::as_date("2001-01-01"))]]
# Extract dates from raster times
dates <- time(rasters) %>% as.character()
substr(dates, 9, 10) <- "01"

# Rename rasters with monthly dates 
names(rasters) <- basename(filePath) %>% 
  substr(1, 33) %>% 
  paste0(.,"_", dates) %>% 
  str_replace(".nc", "")

# Crop rasters to the study extent (+ 10 km buffer)
rasters <- rasters %>%  crop(studyExtent %>%
                               st_transform("EPSG:4326") %>% 
                               st_buffer(10000)) %>%
  # Reproject to GDA94 MGA zone 53
  project("EPSG:28353") %>% 
  # Crop again to remove edge distortion due to reprojection
  crop(studyExtent %>% 
         st_buffer(5000)) 

dates <- time(rasters)
str_sub(dates, -2) <- "01"
time(rasters) <- as_date(dates)
```

# Export rasters

```{r eval = F}
start_date <- time(rasters)[1] %>% 
  str_replace_all("-", "")
end_date <- time(rasters)[length(time(rasters))] %>% 
  str_replace_all("-", "")

writeCDF(rasters, file.path(outputPath, paste0("agcd_v2_preicp_monthly_", start_date, "_", end_date, ".nc")), varname = "agcd_precipitation_monthly", compression = 6, overwrite = T)
```
