---
title: "Unresponsive Pixels"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
pacman::p_load(terra, tidyterra, gganimate, tidyverse, sf)

raster <- rast("./outputs/raster/guerschman_fc_monthly/fc_monthly_pv_20010101_20230101.nc")
study_area <- st_read("./outputs/vector/bonbon_buffer.gpkg") %>% 
  st_transform("EPSG:28353")
ibra_sr <- st_read("./outputs/vector/ibra_subregions.gpkg") %>% 
  st_geometry()
lsys <- st_read("./outputs/vector/pastoral_landsystems.gpkg") %>% 
  .[which(.$OBJECTID == 770),] %>% 
  st_geometry()

plot_studyarea <- function(x) {
  raster <- x[[1]] %>% 
    crop(study_area)
  plot(raster) + plot(study_area, colour = "transparent", add = T)
}

animate(raster)

```

```{r}
min <- tapp(raster[[-265]], index = rep(1:22, each = 12), fun = \(x) min(x, na.rm = T))
max <- tapp(raster[[-265]], index = rep(1:22, each = 12), fun = \(x) max(x, na.rm = T))

diff <- max - min
diff[is.infinite(diff)] <- NA
max_diff <- max(diff)

test <- raster[[1]]
test[max_diff < 8] <- 999

test2 <- raster[[1]]
test2[test1 <= 10] <- 999

plot_studyarea(test2)
```


```{r}
raster <- raster %>% 
  crop(study_area)
ibra_stations <- st_intersection(ibra_sr, study_area) %>% st_union(lsys)

for (i in seq_len(dim(raster)[[3]])) {
  tryCatch({
    plot(raster[[i]]) + 
      plot(ibra_stations, colour = "transparent", add = T)
    }, 
    error = function(e) NULL
  )
}

```


